cosmos-installer: null
name: mongodb4
services:
  "{ServiceName}":
    image: mongo:4.4.22
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: auto
    ports:
      - 27017:27017/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/mongodb4/data/configdb"
        target: /data/configdb
      - type: bind
        source: "{DefaultDataPath}/AppData/mongodb4/data/db"
        target: /data/db
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
