cosmos-installer: null
name: 2fauth
services:
  "{ServiceName}":
    image: 2fauth/2fauth:4.2.4
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    restart: always
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /2fauth
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
