cosmos-installer: {}
name: 2fauth
services:
  "{ServiceName}":
    image: 2fauth/2fauth:4.2.4
    deploy:
      resources:
        reservations:
          memory: 64M
    restart: always
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /2fauth
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
    routes:
      - name: "{ServiceName}"
        description: Expose {ServiceName} to the web
        useHost: true
        target: http://{ServiceName}:8000
        mode: SERVAPP
        Timeout: 14400000
        ThrottlePerMinute: 12000
        BlockCommonBots: true
        SmartShield:
          Enabled: true
minVersion: 0.14.0-0
