cosmos-installer: null
name: databag
services:
  "{ServiceName}":
    image: balzack/databag:0.1.8
    restart: unless-stopped
    ports:
      - 7000:7000/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/databag/data"
        target: /var/lib/databag
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
