cosmos-installer: null
name: portainer
services:
  "{ServiceName}":
    image: portainer/portainer-ce:2.19.4
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: bridge
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
      - 9443:9443/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/portainer"
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
