cosmos-installer: null
version: "3.7"
name: cloudbeaver
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        reservations:
          memory: 256M
    image: dbeaver/cloudbeaver:23.2.4
    ports:
      - 8978:8978/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /opt/cloudbeaver/workspace
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0
