cosmos-installer: null
name: n8n
services:
  "{ServiceName}":
    environment:
      TZ: auto
    image: n8nio/n8n:1.16.0
    deploy:
      resources:
        reservations:
          memory: 320M
    network_mode: bridge
    ports:
      - 5678:5678/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/.n8n"
        target: /home/node/.n8n
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
