cosmos-installer: null
name: homeassistant
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/homeassistant:2023.11.3
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
