cosmos-installer: null
name: stremio
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - NO_CORS=1
    image: stremio/server:4.20.2
    ports:
      - 11470:11470/tcp
      - 12470:12470/tcp
    restart: unless-stopped
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
