cosmos-installer: null
name: overseerr
services:
  "{ServiceName}":
    image: linuxserver/overseerr:1.33.2
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: auto
    ports:
      - 5055:5055/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/overseerr/config"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
