cosmos-installer: null
name: sabnzbd
services:
  "{ServiceName}":
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/sabnzbd:4.1.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8282:8080/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/Downloads"
        target: /incomplete-downloads
      - type: bind
        source: "{DefaultDataPath}/AppData/sabnzbd/config"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/Downloads"
        target: /downloads
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
