cosmos-installer: null
name: wg-easy
services:
  "{ServiceName}":
    image: weejewel/wg-easy:7
    restart: unless-stopped
    network_mode: bridge
    environment:
      PASSWORD: casaos
      WG_HOST: casaos.local
      WG_PORT: "51820"
      WG_DEFAULT_DNS: 1.1.1.1
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/wireguard"
        target: /etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
