cosmos-installer: null
name: siyuan-note
services:
  "{ServiceName}":
    command: --accessAuthCode=casaos --workspace=/siyuan/workspace/
    environment:
      PUID: "1000"
      PGID: "1000"
    image: b3log/siyuan:v2.10.16
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
      - 6806:6806/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/workspace"
        target: /siyuan/workspace
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
