cosmos-installer: null
name: deluge
services:
  "{ServiceName}":
    environment:
      DELUGE_LOGLEVEL: error
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/deluge:2.1.1
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - 8112:8112/tcp
      - 6881:6881/tcp
      - 6881:6881/udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
