cosmos-installer: null
name: plex
services:
  "{ServiceName}":
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    environment:
      PGID: 1000
      PUID: 1000
      VERSION: docker
    image: linuxserver/plex:1.32.8
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/Media"
        target: /Media
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
