cosmos-installer: null
name: bazarr
services:
  "{ServiceName}":
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/bazarr:1.2.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 6767:6767/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{DefaultDataPath}/Media/Movies"
        target: /movies
      - type: volume
        source: "{DefaultDataPath}/Media/TV Shows"
        target: /tv
      - type: volume
        source: "{ServiceName}-data"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
