cosmos-installer: null
name: motioneye
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ccrisan/motioneye:master-amd64
    ports:
      - 8765:8765/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /etc/motioneye
      - type: volume
        source: "{DefaultDataPath}/Media/motioneye"
        target: /var/lib/motioneye
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0
