cosmos-installer: null
name: sickchill
services:
  "{ServiceName}":
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/sickchill:2023.6.27
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8081:8081/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/sickchill/config"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/Downloads"
        target: /downloads
      - type: bind
        source: "{DefaultDataPath}/Media/TV Shows"
        target: /tv
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
