cosmos-installer: null
name: unifi-controller
services:
  "{ServiceName}":
    environment:
      MEM_LIMIT: "1024"
      MEM_STARTUP: "1024"
      PGID: "1000"
      PUID: "1000"
    image: linuxserver/unifi-controller:8.0.7
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8383:8080/tcp
      - 8443:8443/tcp
      - 1900:1900/udp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 6789:6789/tcp
      - 5514:5514/udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
