cosmos-installer: null
name: filedrop
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: noecl/filedrop:1.0.1
    deploy:
      resources:
        reservations:
          memory: 2048M
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /var/file_drop_files
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
