cosmos-installer: null
name: duplicati
services:
  "{ServiceName}":
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/duplicati:2.0.7
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8200:8200/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{DefaultDataPath}/Duplicati/backups"
        target: /backups
      - type: volume
        source: "{DefaultDataPath}/Duplicati/source"
        target: /source
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
