cosmos-installer: null
name: lucky
services:
  "{ServiceName}":
    deploy:
      resources:
        reservations:
          memory: 64M
    image: gdy666/lucky:2.6.2
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /goodluck
    environment:
      TZ: auto
    network_mode: host
    privileged: false
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
