cosmos-installer: null
name: jellyfin
services:
  "{ServiceName}":
    devices:
      - /dev/dri:/dev/dri
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/jellyfin:10.8.12
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - 8097:8096/tcp
      - 8921:8920/tcp
      - 7359:7359/tcp
      - 1901:1900/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{DefaultDataPath}/Media"
        target: /Media
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
