cosmos-installer: null
name: chatgpt-next-web
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
      CODE: ""
      PROXY_URL: ""
      BASE_URL: https://api.openai.com
    image: yidadaa/chatgpt-next-web:v2.8.9
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
