cosmos-installer: null
name: autobrr
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/autobrr/autobrr:v1.30.0
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: auto
    ports:
      - 7474:7474/tcp
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
    hostname: "{ServiceName}"
minVersion: 0.14.0
