cosmos-installer: null
name: emby
services:
  "{ServiceName}":
    devices:
      - /dev/dri:/dev/dri
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: auto
    image: linuxserver/emby:4.7.14
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{DefaultDataPath}/Media/TV Shows"
        target: /data/tvshows
      - type: volume
        source: "{DefaultDataPath}/Media/Movies"
        target: /data/movies
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
