cosmos-installer: null
name: crafty
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: registry.gitlab.com/crafty-controller/crafty-4:4.2.2
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - 8110:8000
      - 8111:8443
      - 8112:8123
      - 19132:19132/udp
      - 25500-25600:25500-25600
    volumes:
      - "{ServiceName}-data"
      - "{ServiceName}-data-2"
      - "{ServiceName}-data-3"
      - "{ServiceName}-data-4"
      - "{ServiceName}-data-5"
    hostname: "{ServiceName}"
minVersion: 0.14.0
