cosmos-installer: null
name: crafty
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: registry.gitlab.com/crafty-controller/crafty-4:4.2.2
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - 8110:8000
      - 8111:8443
      - 8112:8123
      - 19132:19132/udp
      - 25500-25600:25500-25600
    volumes:
      - "{DefaultDataPath}/AppData/crafty/backups:/crafty/backups"
      - "{DefaultDataPath}/AppData/crafty/logs:/crafty/logs"
      - "{DefaultDataPath}/AppData/crafty/servers:/crafty/servers"
      - "{DefaultDataPath}/AppData/crafty/config:/crafty/app/config"
      - "{DefaultDataPath}/AppData/crafty/import:/crafty/import"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
