cosmos-installer: null
name: cloudflared
services:
  "{ServiceName}":
    image: wisdomsky/cloudflared-web:2023.10.0
    restart: unless-stopped
    network_mode: host
    ports:
      - 14333:14333/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/casaos-cloudflared/config"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
