cosmos-installer: null
name: readarr
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/readarr:0.3.10-develop
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8787:8787/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{DefaultDataPath}/Media/Books"
        target: /books
      - type: volume
        source: "{DefaultDataPath}/Downloads"
        target: /downloads
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
