cosmos-installer: null
name: threadfin
services:
  "{ServiceName}":
    image: fyb3roptik/threadfin:latest
    restart: unless-stopped
    environment:
      - THREADFIN_BRANCH=main
      - THREADFIN_DEBUG=0
    ports:
      - 34400:34400/tcp
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /home/threadfin/conf/data
      - type: volume
        source: "{ServiceName}-data-2"
        target: /home/threadfin/conf/backup
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
