cosmos-installer: null
name: threadfin
services:
  "{ServiceName}":
    image: fyb3roptik/threadfin:latest
    restart: unless-stopped
    environment:
      - THREADFIN_BRANCH=main
      - THREADFIN_DEBUG=0
    ports:
      - 34400:34400/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/threadfin/config"
        target: /home/threadfin/conf/data
      - type: bind
        source: "{DefaultDataPath}/AppData/threadfin/backup"
        target: /home/threadfin/conf/backup
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
