cosmos-installer: null
name: navidrome
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        reservations:
          memory: 1024M
    image: deluan/navidrome:0.50.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Navidrome/icon.png
    restart: always
    ports:
      - 4533:4533/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/data"
        target: /data
      - type: bind
        source: "{DefaultDataPath}/Media/Music"
        target: /music
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      TZ: auto
    network_mode: host
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
