cosmos-installer: null
name: medusa
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        limits:
          memory: 7848M
    environment:
      - TZ= auto
    image: pymedusa/medusa:master
    ports:
      - 8081:8081/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{ServiceName}-data-2"
        target: /downloads
      - type: volume
        source: "{ServiceName}-data-3"
        target: /tv
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0
