cosmos-installer: null
name: medusa
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        limits:
          memory: 7848M
    environment:
      - TZ= auto
    image: pymedusa/medusa:master
    ports:
      - 8081:8081/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/Downloads/Television"
        target: /downloads
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/Media/Television"
        target: /tv
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
