cosmos-installer: null
name: homebridge
version: "2"
services:
  "{ServiceName}":
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - "{DefaultDataPath}/AppData/{ServiceName}/config:/homebridge"
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: "1"
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: homebridge
  author: UnderCurve
  category: Home Automation
  description:
    en_us: Homebridge is a lightweight NodeJS server you can run on your home
      network that emulates the iOS HomeKit API. It supports Plugins, which are
      community-contributed modules that provide a basic bridge from HomeKit to
      various 3rd-party APIs provided by manufacturers of "smart home" devices.
    zh_cn: Homebridge是一个轻量级的NodeJS服务器，您可以在家庭网络中运行它，模拟iOS HomeKit
      API。它支持插件，这是由社区贡献的模块，提供了从HomeKit到各种由“智能家居”设备制造商提供的第三方API的基本桥梁。
  developer: Homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/screenshot-2.png
  tagline:
    en_us: HomeKit support for the impatient.
    zh_cn: HomeKit 为急性子提供支持
  title:
    en_us: Homebridge
  index: /
  port_map: "8581"
minVersion: 0.14.0
