cosmos-installer: null
name: homebridge
version: "2"
services:
  "{ServiceName}":
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - "{DefaultDataPath}/AppData/{ServiceName}/config:/homebridge"
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: "1"
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
