cosmos-installer: null
name: vaultwarden
services:
  "{ServiceName}":
    image: vaultwarden/server:1.30.1
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - 10380:80/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /data
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
