cosmos-installer: null
name: memos
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: neosmemo/memos:0.18.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 5230:5230/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /var/opt/memos
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
