cosmos-installer: null
name: emulatorjs
services:
  "{ServiceName}":
    environment:
      - PGID=1000
      - PUID=1000
      - SUBFOLDER=/
      - TZ=auto
    image: linuxserver/emulatorjs:1.7.2
    network_mode: bridge
    ports:
      - 3001:3000/tcp
      - 4001:4001/tcp
      - 88:80/tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
      - type: volume
        source: "{ServiceName}-data-2"
        target: /data
      - type: bind
        source: /ROMS/nes
        target: /data/nes/roms
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
