cosmos-installer: null
name: media-fetch-pro
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: correctroad/media-fetch-pro:0.3.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 7789:7789/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/Media/MediaFetchPro"
        target: /var/opt/video
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /var/opt/config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
