cosmos-installer: null
name: esphome
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    deploy:
      resources:
        reservations:
          memory: 512M
    image: ghcr.io/esphome/esphome:2023.9
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/icon.png
    restart: always
    ports:
      - 6052:6052/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
    environment:
      ESPHOME_DASHBOARD_USE_PING: "false"
      TZ: auto
    network_mode: host
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
