cosmos-installer: null
name: twingate-connector
services:
  "{ServiceName}":
    image: twingate/connector:1
    container_name: "{ServiceName}"
    command:
      - /connectord
    environment:
      TWINGATE_NETWORK: ""
      TWINGATE_ACCESS_TOKEN: ""
      TWINGATE_REFRESH_TOKEN: ""
      TWINGATE_LABEL_HOSTNAME: ${HOSTNAME}
    restart: unless-stopped
    sysctls:
      net.ipv4.ping_group_range: 0 2147483647
    network_mode: default
    privileged: false
    cpu_shares: 90
    deploy:
      resources:
        reservations:
          memory: 500M
    hostname: "{ServiceName}"
minVersion: 0.14.0
