cosmos-installer: null
name: resilio-sync
services:
  "{ServiceName}":
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=auto
    image: linuxserver/resilio-sync:2.7.3
    network_mode: bridge
    ports:
      - 55555:55555/tcp
      - 8888:8888/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/data"
        target: /sync
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/Downloads"
        target: /downloads
    privileged: false
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
