cosmos-installer: null
name: calibre-web
services:
  "{ServiceName}":
    environment:
      DOCKER_MODS: ghcr.io/linuxserver/mods:universal-calibre
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/calibre-web:0.6.21
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8083:8083/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/{ServiceName}/config"
        target: /config
      - type: bind
        source: "{DefaultDataPath}/Media/Books"
        target: /books
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
