cosmos-installer: null
name: adguard-home
services:
  "{ServiceName}":
    image: adguard/adguardhome:v0.107.41
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 531:53/tcp
      - 531:53/udp
      - 3001:3000/tcp
      - 853:853/tcp
      - 784:784/udp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /opt/adguardhome/work
      - type: volume
        source: "{ServiceName}-data-2"
        target: /opt/adguardhome/conf
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
