cosmos-installer: null
name: petio
services:
  "{ServiceName}-petio":
    image: ghcr.io/petio-team/petio@sha256:1c5a9276a844f4284601cbe332905864950545ebdeaad74bacb9097ea4f4b333
    restart: unless-stopped
    networks:
      - petio-network
    depends_on:
      - mongo
    environment:
      PUID: 1000
      PGID: 1000
      TZ: auto
    ports:
      - 7777:7777/tcp
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/petio/config"
        target: /app/api/config
      - type: bind
        source: "{DefaultDataPath}/AppData/petio/logs"
        target: /app/logs
    container_name: "{ServiceName}-petio"
    hostname: "{ServiceName}-petio"
  "{ServiceName}-mongo":
    image: mongo:4.4.22
    restart: unless-stopped
    hostname: "{ServiceName}-mongo"
    networks:
      - petio-network
    environment:
      PUID: 1000
      PGID: 1000
      TZ: auto
    container_name: "{ServiceName}-mongo"
networks:
  petio-network:
    driver: bridge
minVersion: 0.14.0-0
