cosmos-installer: null
name: openspeedtest
services:
  "{ServiceName}":
    image: openspeedtest/latest:v0.0.1
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 3004:3000/tcp
    restart: always
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
