cosmos-installer: null
name: netdata
services:
  "{ServiceName}":
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    cpu_shares: 90
    container_name: "{ServiceName}"
    deploy:
      resources:
        limits:
          memory: 1794M
    image: netdata/netdata:stable
    labels:
      icon: https://icon.casaos.io/main/all/netdata.png
    pid: host
    ports:
      - 19999:19999/tcp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: "{DefaultDataPath}/AppData/Netdata/config"
        target: /etc/netdata
      - type: bind
        source: "{DefaultDataPath}/AppData/Netdata/lib"
        target: /var/lib/netdata
      - type: bind
        source: "{DefaultDataPath}/AppData/Netdata/cache"
        target: /var/cache/netdata
      - type: bind
        source: /etc/passwd
        target: /host/etc/passwd
      - type: bind
        source: /etc/group
        target: /host/etc/group
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: /etc/os-release
        target: /host/etc/os-release
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: bridge
    privileged: false
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
