cosmos-installer: null
name: chatbot-ui
services:
  "{ServiceName}":
    environment:
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    network_mode: bridge
    ports:
      - 3080:3000/tcp
    restart: unless-stopped
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
