cosmos-installer: null
name: lazylibrarian
services:
  "{ServiceName}":
    environment:
      DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
      PGID: 1000
      PUID: 1000
      TZ: auto
    image: linuxserver/lazylibrarian:version-0ca9b70c
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 5299:5299/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{DefaultDataPath}/Downloads"
        target: /downloads
      - type: volume
        source: "{DefaultDataPath}/Media/Books"
        target: /books
      - type: volume
        source: "{ServiceName}-data"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
