cosmos-installer: null
name: mariadb
services:
  "{ServiceName}":
    image: linuxserver/mariadb:10.11.5
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: auto
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      REMOTE_SQL: ""
    ports:
      - 3306:3306/tcp
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
