cosmos-installer: null
name: tautulli
services:
  "{ServiceName}":
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/tautulli:2.13.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - 8181:8181
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /config
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
