cosmos-installer: null
name: nextcloud
services:
  "{ServiceName}":
    image: nextcloud:27.1.3
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
      - 10081:80/tcp
      - 10443:443/tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /var/www/html
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
